FROM node:24-alpine

WORKDIR /app
RUN chown node:node /app

USER node

COPY --chown=node:node package.json package-lock.json ./
COPY --chown=node:node packages/latte-core/package.json ./packages/latte-core/package.json
RUN npm ci

COPY --chown=node:node . .

EXPOSE 5173

CMD ["./bash/docker-dev-entrypoint.sh"]
