services:
  burro:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: burro
    restart: unless-stopped
    ports:
      - "127.0.0.1:5173:5173"
    env_file:
      - .env.docker
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - pane

networks:
  pane:
    external: true
    name: pane_laravel
